name: "All Contributors Bot"

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]

jobs:
  add-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run all-contributors action
        uses: all-contributors/all-contributors-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
